OK_PROCESSED = "OK_PROCESSED"
OK_ALREADY_PROCESSED = "OK_ALREADY_PROCESSED"

ERR_INVALID_SCHEMA = "ERR_INVALID_SCHEMA"
ERR_INVALID_CHAIN_ID = "ERR_INVALID_CHAIN_ID"
ERR_INVALID_NONCE = "ERR_INVALID_NONCE"
ERR_STALE_MESSAGE = "ERR_STALE_MESSAGE"
ERR_EXPIRED_MESSAGE = "ERR_EXPIRED_MESSAGE"
ERR_INVALID_PROOF = "ERR_INVALID_PROOF"
ERR_UNAUTHORIZED_ACTOR = "ERR_UNAUTHORIZED_ACTOR"
ERR_INVALID_STATE_TRANSITION = "ERR_INVALID_STATE_TRANSITION"
ERR_PROCESSING_FAILED = "ERR_PROCESSING_FAILED"

ALL_CODES = {
    OK_PROCESSED,
    OK_ALREADY_PROCESSED,
    ERR_INVALID_SCHEMA,
    ERR_INVALID_CHAIN_ID,
    ERR_INVALID_NONCE,
    ERR_STALE_MESSAGE,
    ERR_EXPIRED_MESSAGE,
    ERR_INVALID_PROOF,
    ERR_UNAUTHORIZED_ACTOR,
    ERR_INVALID_STATE_TRANSITION,
    ERR_PROCESSING_FAILED,
}
